# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-17 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_auto_20160629_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invite_type',
            field=models.CharField(choices=[('Gast', 'Gast')], default='Gast', max_length=20),
        ),
    ]
