# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-17 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenv2',
            options={'managed': False},
        ),
    ]
