# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-22 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0002_auto_20201017_1312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tokenv2',
            table='api3_tokenv2',
        ),
    ]
