# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyUserTraffic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('org_id', models.IntegerField()),
                ('month', models.DateField()),
                ('web_file_upload', models.BigIntegerField()),
                ('web_file_download', models.BigIntegerField()),
                ('sync_file_upload', models.BigIntegerField()),
                ('sync_file_download', models.BigIntegerField()),
                ('link_file_upload', models.BigIntegerField()),
                ('link_file_download', models.BigIntegerField()),
            ],
            options={
                'db_table': 'MonthlyUserTraffic',
                'managed': True,
            },
        ),
    ]
