# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0002_add_monthly_user_traffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirusScannedHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_id', restapi.base.fields.LowerCaseCharField(max_length=36)),
                ('scanned_head_id', restapi.base.fields.LowerCaseCharField(max_length=255)),
            ],
            options={
                'db_table': 'VirusScannedHeader',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VirusScanningInfectedFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_id', restapi.base.fields.LowerCaseCharField(max_length=36)),
                ('infected_file_path', models.TextField(max_length=1024)),
                ('is_handled', models.BooleanField(default=False)),
                ('is_false_positive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'VirusScanningInfectedFile',
                'managed': True,
            },
        ),
    ]
