# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-13 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api3', '0007_email_changing_request_column_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('folder', models.TextField(blank=True, null=True)),
                ('sub_folder_file', models.TextField(blank=True, null=True)),
                ('action_type', models.TextField(blank=True, null=True)),
                ('recipient', models.TextField(blank=True, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AuditLog',
            },
        )
    ]
