# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-13 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0008_auto_20200213_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='name',
            field=models.TextField(blank=True, null=True),
        )
    ]
