# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-13 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0009_auto_20200213_0822'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='auditlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
