# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-20 03:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0011_auto_20200220_0326'),
    ]

    operations = [
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX AuditLog_name_fulltext ON AuditLog(name);
                """
            )],
            [(
                """
                DROP INDEX AuditLog_name_fulltext ON AuditLog;
                """
            )]
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX AuditLog_folder_fulltext ON AuditLog(folder);
                """
            )],
            [(
                """
                DROP INDEX AuditLog_folder_fulltext ON AuditLog;
                """
            )]
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX AuditLog_sub_folder_file_fulltext ON AuditLog(sub_folder_file);
                """
            )],
            [(
                """
                DROP INDEX AuditLog_sub_folder_file_fulltext ON AuditLog;
                """
            )]
            
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX AuditLog_recipient_fulltext ON AuditLog(recipient);
                """
            )],
            [(
                """
                DROP INDEX AuditLog_recipient_fulltext ON AuditLog;
                """                
            )]            
        ),
    ]
