# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-13 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0012_add_audit_log_fulltext_index'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, db_index=True, max_length=45, null=True),
        ),

    ]
