# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-09 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0014_auto_20200313_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('folder', models.TextField(blank=True, null=True)),
                ('folder_id', models.TextField(blank=True, null=True)),
                ('sub_folder_file', models.TextField(blank=True, null=True)),
                ('action_type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('recipient', models.TextField(blank=True, null=True)),
                ('permissions', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'UserActivity',
            },
        )
    ]
