# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-16 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0015_auto_20200409_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='device_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='device_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX AuditLog_folder_id_fulltext ON AuditLog(folder_id);
                """
            )],
            [(
                """
                DROP INDEX AuditLog_folder_id_fulltext ON AuditLog;
                """
            )]
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX AuditLog_device_name_fulltext ON AuditLog(device_name);
                """
            )],
            [(
                """
                DROP INDEX AuditLog_device_name_fulltext ON AuditLog;
                """
            )]
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX UserActivity_name_fulltext ON UserActivity(name);
                """
            )],
            [(
                """
                DROP INDEX UserActivity_name_fulltext ON UserActivity;
                """
            )]
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX UserActivity_folder_fulltext ON UserActivity(folder);
                """
            )],
            [(
                """
                DROP INDEX UserActivity_folder_fulltext ON UserActivity;
                """
            )]
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX UserActivity_sub_folder_file_fulltext ON UserActivity(sub_folder_file);
                """
            )],
            [(
                """
                DROP INDEX UserActivity_sub_folder_file_fulltext ON UserActivity;
                """
            )]
            
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX UserActivity_recipient_fulltext ON UserActivity(recipient);
                """
            )],
            [(
                """
                DROP INDEX UserActivity_recipient_fulltext ON UserActivity;
                """                
            )]            
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX UserActivity_device_name_fulltext ON UserActivity(device_name);
                """
            )],
            [(
                """
                DROP INDEX UserActivity_device_name_fulltext ON UserActivity;
                """                
            )]            
        ),
        migrations.RunSQL(
            [(
                """
                CREATE FULLTEXT INDEX UserActivity_folder_id_fulltext ON UserActivity(folder_id);
                """
            )],
            [(
                """
                DROP INDEX UserActivity_folder_id_fulltext ON UserActivity;
                """
            )]
        ),
    ]
