# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-16 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from restapi.settings import DEFAULT_EVENT_LOG_DEVICE_NAME
import restapi.base.fields

def update_audit_log_device_name(apps, schema_editor):
    AuditLog = apps.get_model("api3", "AuditLog")
    AuditLog.objects.filter(device_name=None).update(device_name=DEFAULT_EVENT_LOG_DEVICE_NAME)


def update_user_activity_device_name(apps, schema_editor):
    UserActivity = apps.get_model("api3", "UserActivity")
    UserActivity.objects.filter(device_name=None).update(device_name=DEFAULT_EVENT_LOG_DEVICE_NAME)

class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0016_auto_20200416_0500'),
    ]

    operations = [
        migrations.RunPython(update_audit_log_device_name),
        migrations.RunPython(update_user_activity_device_name),
    ]
