# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-07 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0017_migrate_null_device_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('attendee_pw', models.CharField(max_length=255)),
                ('moderator_pw', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=16, default="STOPPED")),
                ('owner_id', models.CharField(max_length=255)),
                ('b3_meeting_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'MeetingRooms',
            },
        )
    ]
