# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-11 08:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0018_create_meeting_room_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='MeetingRoom',
            name='share_token',
            field=models.CharField(max_length=32, blank=True, null=True, default=None, unique=True),
        ),
    ]
