# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-18 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0019_add_column_to_meeting_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='MeetingRoom',
            name='mute_participants_on_join',
            field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name='MeetingRoom',
            name='require_mod_approval',
            field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name='MeetingRoom',
            name='allow_any_user_start',
            field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name='MeetingRoom',
            name='all_users_join_as_mod',
            field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name='MeetingRoom',
            name='allow_recording',
            field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name='MeetingRoom',
            name='max_number_of_participants',
            field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name='MeetingRoom',
            name='welcome_message',
            field=models.TextField()
        ),

    ]
