# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-22 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0020_add_more_info_to_meeting_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBPrivateSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bbb_server', models.TextField()),
                ('bbb_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('group_id', models.IntegerField(null=True)),
                ('tenant_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'BBBPrivateSettings',
            },
        )
    ]
