# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-26 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0021_add_private_bbb_server_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_room_id', models.IntegerField(null=False)),
                ('share_to_user', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'MeetingRoomShares',
                'managed': True,
            },
        )
    ]
