# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-02 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0022_add_meeting_room_private_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='MeetingRoomShare',
            name='group_id',
            field=models.IntegerField()
        ),
        migrations.AddField(
            model_name='MeetingRoomShare',
            name='share_type',
            field=models.CharField(max_length=30, default="SHARED_TO_USER")
        ),
    ]
