# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-08 07:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0024_add_meeting_setting_id_to_meeting_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='MeetingRoom',
            name='require_meeting_password',
            field=models.BooleanField(default=False)
        ),
    ]
