# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-15 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0025_add_option_to_force_user_to_provide_meeting_key_before_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='BBBPrivateSetting',
            name='setting_name',
            field=models.CharField(max_length=255, default="Unammed configuration")
        ),
        migrations.RemoveField(
            model_name='BBBPrivateSetting',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='BBBPrivateSetting',
            name='tenant_id',
        ),
        migrations.RunSQL(
            """
            TRUNCATE TABLE `BBBPrivateSettings`;
            """
        ),
        migrations.RunSQL(
            """
            UPDATE `MeetingRooms` set `private_setting_id` = -1;
            """
        )
    ]
