# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-08 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0026_manipulate_bbb_private_setting_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254, unique=True)),
                ('max_meetings', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ProfileSetting',
            },
        ),
    ]
