# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-23 03:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0028_add_presentation_file_to_meeting_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_room_id', models.IntegerField()),
                ('presentation_file', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MeetingRoomFile',
            },
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='presentation_file',
        ),
    ]
