# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-22 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0029_add_multi_file_to_meeting_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingroomshare',
            options={},
        ),
        migrations.AlterField(
            model_name='bbbprivatesetting',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='meetingroomshare',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
