# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-22 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0031_auto_20201022_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_index=True, max_length=255)),
                ('owner_id', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default=b'', upload_to=b'kanban/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'KanbanProject',
            },
        ),
    ]
