# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-22 14:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0035_auto_20201022_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(db_index=True, max_length=255)),
                ('board_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kanban_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api3.KanbanProject')),
            ],
            options={
                'db_table': 'KanbanBoard',
            },
        ),
    ]
