# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-22 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0039_auto_20201022_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanSubTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='kanbantask',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='api3.KanbanSubTask'),
        ),
    ]
