# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0042_auto_20201119_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbantask',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='kanbantask',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
