# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import restapi.api3.models


def assign_random_colors(apps, schema):
    KanbanTag = apps.get_model('api3.KanbanTag')
    for tag in KanbanTag.objects.all():
        tag.color = restapi.api3.models.random_color()
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0043_auto_20201214_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbantag',
            name='color',
            field=models.CharField(default=restapi.api3.models.random_color, max_length=6),
        ),
        migrations.RunPython(assign_random_colors, lambda apps, schema: None, elidable=True),
    ]
