# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0044_kanbantag_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[(b'U', b'Shared to User'), (b'G', b'Shared to Group')], default=b'U', max_length=2)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.CharField(choices=[(b'r', b'Read-only'), (b'rw', b'Read/Write')], default=b'r', max_length=4)),
                ('kanban_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api3.KanbanProject')),
            ],
        ),
        migrations.RemoveField(
            model_name='kanbanmember',
            name='kanban_project',
        ),
        migrations.AlterField(
            model_name='kanbantag',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='KanbanMember',
        ),
        migrations.AlterUniqueTogether(
            name='kanbanshare',
            unique_together=set([('kanban_project', 'user_id')]),
        ),
    ]
