# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-24 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import restapi.api3.models
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0045_auto_20201224_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanShareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', restapi.base.fields.LowerCaseCharField(max_length=255)),
                ('token', models.CharField(default=restapi.api3.models.make_random_token, max_length=100, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('view_cnt', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=128, null=True)),
                ('expire_date', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api3.KanbanProject')),
            ],
        ),
    ]
