# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-04 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0046_kanbansharelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api3.KanbanTask')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='kanbansubscription',
            unique_together=set([('task', 'user_id')]),
        ),
    ]
