# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-05 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0047_auto_20210104_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='live_stream_active',
            field=models.BooleanField(default=False),
        ),
    ]
