# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-22 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0049_bbbprivatesetting_live_stream_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='live_stream_feedback_active',
            field=models.BooleanField(default=False),
        ),
    ]
