# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0050_meetingroom_live_stream_feedback_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='live_stream_meeting_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='live_stream_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
