# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-03-02 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0051_auto_20210222_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbprivatesetting',
            name='live_stream_server',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
