# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-28 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import restapi.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileLocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_id', restapi.base.fields.LowerCaseCharField(max_length=36)),
                ('path', models.CharField(max_length=1024)),
                ('email', models.CharField(db_column=b'user_name', max_length=255)),
                ('lock_time', models.BigIntegerField()),
                ('expire', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'FileLocks',
            },
        ),
        migrations.CreateModel(
            name='FileLockTimestamp',
            fields=[
                ('repo_id', restapi.base.fields.LowerCaseCharField(max_length=36, primary_key=True, serialize=False)),
                ('update_time', models.BigIntegerField()),
            ],
            options={
                'db_table': 'FileLockTimestamp',
            },
        ),
        migrations.CreateModel(
            name='SharedRepo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_id', restapi.base.fields.LowerCaseCharField(max_length=36)),
                ('from_email', models.CharField(max_length=255)),
                ('to_email', models.CharField(max_length=255)),
                ('permission', models.CharField(max_length=255)),
                ('allow_view_history', models.BooleanField()),
                ('allow_view_snapshot', models.BooleanField()),
                ('allow_restore_snapshot', models.BooleanField()),
            ],
            options={
                'db_table': 'SharedRepo',
            },
        ),
    ]
