# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-17 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('syncwerk_server_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderBranch',
            fields=[
                ('name', models.CharField(max_length=1024)),
                ('repo_id', restapi.base.fields.LowerCaseCharField(max_length=36, primary_key=True, serialize=False)),
                ('commit_id', restapi.base.fields.LowerCaseCharField(max_length=256)),
            ],
            options={
                'db_table': 'Branch',
            },
        ),
        migrations.DeleteModel(
            name='SharedRepo',
        ),
    ]
