# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 07:10
from __future__ import unicode_literals

from django.db import migrations
import restapi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantadmin',
            name='user',
            field=restapi.base.fields.LowerCaseCharField(db_index=True, max_length=255),
        ),
    ]
